language: php
php:
  - '5.6'

env:
  - DB=MYSQL CORE_RELEASE=3.2

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - "vendor/bin/phpunit seo-hero-tool-analysis/tests"
